### ISSUE TITLE
first exercise section in Chapter 2 missing, at least from table of contents

### ISSUE THREAD

**Issue by sklarjk** [sklarjk/sklaraa#12]
See Section 2.2 in the attached PDF.

[sklaraa.pdf](https://github.com/sklarjk/sklaraa/files/1175178/sklaraa.pdf)

It's missing in the HTML toc:
https://community.plu.edu/~sklarjk/ptx/

Maybe this is something I should figure out how to fix myself?

**Comment by davidfarmer** [comment]
Can you provide a link to the specific page?  I am not sure what to
look for.

**Comment by sklarjk** [comment]
I'm not sure what you're asking for. The HTML  page is the table of
contents, which is missing the section titled Exercises, Part I, in Chapter

https://community.plu.edu/~sklarjk/ptx/

You can see that section listed in the navigation menu and table of
contents is the PDF.

If this isn't sufficient, can you tell me what you need? A screenshot of
the toc of the PDF? It looks like a section just wasn't inclued in the
index.ptx code or the like?

On Jul 25, 2017 6:56 PM, "davidfarmer" <notifications@github.com> wrote:


Can you provide a link to the specific page? I am not sure what to
look or.

On Wed, 26 Jul 2017, Jessica K. Sklar wrote:

>
> See Section 2.2 in the attached PDF.
>
> sklaraa.pdf
>
> It's missing in the HTML toc:
> https://community.plu.edu/~sklarjk/ptx/
>
> Maybe this is something I should figure out how to fix myself?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AAM6LNhwrwrRoPfKfKlV5TFIIURTvE_Eks5sRo7DgaJpZM4OjTMq.gif]
>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sklarjk/sklaraa/issues/12#issuecomment-317924140>, or mute
the thread

**Comment by davidfarmer** [comment]
My guess is that there is an xslt error in theprocessing of that
section, which is why it does not appear.

**Comment by sklarjk** [comment]
Ah, I figured out the xslt processing error (an invalid symbol) and why you were confused: the chapter numbering in the original PDF and in the HTML is different.  It's fixed now.
