### ISSUE TITLE
Use "term" tags when defining notation: Must fix Chap 7 on

### ISSUE THREAD

**Issue by davidfarmer** [sklarjk/sklaraa#15]
Some of the places where you use "em" should be "term", to indicate
that terminology is being defined.  For example, in this sentence

Although it is written in what we call  <em>multiplicative
notation</em>,

in section2-5.ptx .

The other "em" in that paragraph should stay as an "em", because it really is *emphasis*.

**Comment by davidfarmer** [comment]
It changes the appearance, and also will be used by some planned
features.

This feature is not in PTX yet, but if you look here:

http://sl2x.aimath.org/latexsource/sklaraa/sklaraa/html1/section5-1.html

and hover your mouse over various words, if that word is a "term"
somewhere, then you can click to see the definition.  (Works
in Firefox, and probably in Chrome, but does not work well in Safari.)

**Comment by sklarjk** [comment]
Completed July 29 2017.
