### ISSUE TITLE
remove <title>print=false</title> and/or <title>print=false</title> from files

### ISSUE THREAD

**Issue by sklarjk** [sklarjk/sklaraa#22]
David, some of my PTX files contain these useless strings (they were used to hide/show solutions in the PDF I compiled from LaTeX).  Would it be easy for  you to  remove these en masse?  If not, I can remove them one at a time. Thanks!

**Comment by davidfarmer** [comment]
I didn't encounter those when browsing; do they happen a lot?
If it is only a dozen times or so, then it is easiest to just remove
them as you edit the file.  At some point you will end up editing every
file (probably several times!)

**Comment by sklarjk** [comment]
They show up a number of times but only in the exercise files, so I can
easily remove them individually. Thanks!

On Jul 27, 2017 10:36 AM, "davidfarmer" <notifications@github.com> wrote:


I didn't encounter those when browsing; do they happen a lot?
If it is only a dozen times or so, then it is easiest to just remove
them as you edit the file. At some point you will end up editing every
file (probably several times!)

On Thu, 27 Jul 2017, Jessica K. Sklar wrote:

>
> David, some of my PTX files contain these useless strings (they were used
to hide/show solutions in the PDF I compiled
> from LaTeX). Would it be easy for you to remove these en masse? If not, I
can remove them one at a time. Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AAM6LAld60gWeXdziglhEFllu8AEgBxLks5sSMd_gaJpZM4Oll6k.gif]
>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sklarjk/sklaraa/issues/22#issuecomment-318432795>, or mute
the thread

**Comment by sklarjk** [comment]
Completed.
