### ISSUE TITLE
Example labels appearing in HTML 

### ISSUE THREAD

**Issue by sklarjk** [sklarjk/sklaraa#6]
For example: {homos} is printed at the beginning of Example 4.2.4, and the reference to the example, above it, doesn't work properly (<<Unresolved xref, reference "homos"; check spelling or use "provisional" attribute>>)

https://community.plu.edu/~sklarjk/ptx/section-15.html

This happens whenever an example is labeled so it can be referred to elsewhere by number. "homos" was the LaTeX reference label for the example.

**Comment by davidfarmer** [comment]
In the next pull request, those will be converted to labels.

**Comment by sklarjk** [comment]
These seem fixed when posted online.  But oddly, if I look at the book locally on my laptop, the example reference link doesn't take you you to the example.  See the attached screenshot.
![exampless](https://user-images.githubusercontent.com/30130540/28599251-dd8fc45c-715d-11e7-8a24-99b4edb8df6e.jpg)

**Comment by davidfarmer** [comment]
Depending on the browser you use, knowls may not work properly
when viewed locally.  (Part of the issues is that there is not actual
web server: just viewing a bunch of files.)

**Comment by sklarjk** [comment]
Ah, ok.  Should I commit the changes then?  And close this thread?  (I promise I'll stop asking so many questions as I get more of the feel for this.)

**Comment by davidfarmer** [comment]
I think you should commit and close the issue, but it is
your book and your decision!
