### ISSUE TITLE
delete colons after Exercise titles

### ISSUE THREAD

**Issue by sklarjk** [sklarjk/sklaraa#7]
E.g.: 
https://community.plu.edu/~sklarjk/ptx/section-9.html

I like the colons in my LaTeXed PDF, but not in the PTX format. This is obviously something I could change on a case-by-case basis if needed.

**Comment by davidfarmer** [comment]
First decide whether you want the examples hidden in knowls by default.
If you do wnat them hidden, then probably you need to put a title
on each of them.

**Comment by sklarjk** [comment]
Good point.  I actually do not want them hidden.

**Comment by sklarjk** [comment]
Is this something you can change systemically, so all the examples appear like definitions, with the word "Example" instead of "Definition."?  There are a lot of examples to change by hand.  Thank you!

**Comment by davidfarmer** [comment]
Not sure I understand what you mean.

When you compile the HTML, you can choose to have the examples visible
instead of hidden in knowls.  This has nothing to do with the source: it is
ow you convert the source to HTML.

If you meant something different, please clarify.

**Comment by sklarjk** [comment]
OK, I don't know how to compile it any differently than the way it compiles
using the command you sent me. The way I have been compiling it, the
definitions (at least  most of them) aren't hidden, but all the examples
are.

I don't know what knowls is. I never used any of this before this week.
Sorry.

Jess

On Jul 25, 2017 6:53 PM, "davidfarmer" <notifications@github.com> wrote:

Not sure I understand what you mean.

When you compile the HTML, you can choose to have the examples visible
instead of hidden in knowls. This has nothing to do with the source: it is
ow you convert the source to HTML.

If you meant something different, please clarify.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sklarjk/sklaraa/issues/7#issuecomment-317923732>, or mute
the thread

**Comment by davidfarmer** [comment]
A knowl is the thing with the dotted underline that expands
when you click on it.

I don't recall the details, but you can control which environments
are in knowls.

Maybe a posting to the google group, explaining that the documentation
does not make it clear how to set which things are in knowls, would
help.

**Comment by sklarjk** [comment]
I finally figured it out.  The key thing I couldn't find anywhere in the documentation was that I had to change the mathbook-html.xls file.  Had I only opened it ....
