### ISSUE TITLE
\fbox's not compiling correctly

### ISSUE THREAD

**Issue by sklarjk** [sklarjk/sklaraa#9]
E.g., the second line should have the text in a box, not in \fbox{}.

https://community.plu.edu/~sklarjk/ptx/section-29.html

**Comment by davidfarmer** [comment]
Since fbox only occurs a few times, you will need to fix
them by hand, later, after the automated phase is completed.

You will need to mark them in some structural/semantic way.
Do not think in therms of a literal "box", but in terms
of the purpose that the box served.

**Comment by sklarjk** [comment]
Sounds good.

**Comment by davidfarmer** [comment]
I suggest you keep the issue open, as a reminder to fix it later.

You can organize your issues into milestones, assign people
to fix them, and so on.

**Comment by sklarjk** [comment]
Ok!

**Comment by sklarjk** [comment]
I will deal with these, so closing out this thread.
